// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgt119vi7J7Y6VTEvLK9mrk2wuaibk_9Y',
    appId: '1:982794985339:web:71a356a1c5a44e3811a7de',
    messagingSenderId: '982794985339',
    projectId: 'myproject-c4acc',
    authDomain: 'myproject-c4acc.firebaseapp.com',
    storageBucket: 'myproject-c4acc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzz3CfDF0TNL_v6zITJV0GlQtlBLJ4svg',
    appId: '1:982794985339:android:5aa274f1785c88ad11a7de',
    messagingSenderId: '982794985339',
    projectId: 'myproject-c4acc',
    storageBucket: 'myproject-c4acc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEn9KoRCnIVK91yNLDMCtCniolIFtbOa4',
    appId: '1:982794985339:ios:486c374e3584ad8c11a7de',
    messagingSenderId: '982794985339',
    projectId: 'myproject-c4acc',
    storageBucket: 'myproject-c4acc.appspot.com',
    iosBundleId: 'com.example.firbaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEn9KoRCnIVK91yNLDMCtCniolIFtbOa4',
    appId: '1:982794985339:ios:486c374e3584ad8c11a7de',
    messagingSenderId: '982794985339',
    projectId: 'myproject-c4acc',
    storageBucket: 'myproject-c4acc.appspot.com',
    iosBundleId: 'com.example.firbaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgt119vi7J7Y6VTEvLK9mrk2wuaibk_9Y',
    appId: '1:982794985339:web:13cc243597f21c7111a7de',
    messagingSenderId: '982794985339',
    projectId: 'myproject-c4acc',
    authDomain: 'myproject-c4acc.firebaseapp.com',
    storageBucket: 'myproject-c4acc.appspot.com',
  );
}
